### ISSUE TITLE
Count mismatch from dashboard to identities

### ISSUE THREAD

**Issue by dovholuknf** [netfoundry/ziti-console#2]
I made the same user many times. The dashboard shows me '8' identities yet the identities page only shows one.

![image](https://user-images.githubusercontent.com/46322585/73268749-88e1cf80-41a9-11ea-80c2-fec4ddeb423c.png)

![image](https://user-images.githubusercontent.com/46322585/73268790-9434fb00-41a9-11ea-8a8e-9d465805f067.png)

**Comment by netfoundry-ui** [comment]
Issue with Edge Controller Paging, will be fixed at the service level.
