### ISSUE TITLE
Services shows wrong 'type'

### ISSUE THREAD

**Issue by dovholuknf** [netfoundry/ziti-console#3]
* make two service policies
* 'edit' the dial-all policy
* notice the dial-all policy has 'bind' as the type

```
id: 67d35a08-f6c9-4392-972e-de14cdbad97c    name: bind-all    type: Bind    service roles: ["@all"]    identity roles: ["@all"]
id: 827b7fb3-51e5-471e-91d0-4b0973b76ac3    name: dial-all    type: Dial    service roles: ["@all"]    identity roles: ["@all"]
```
![image](https://user-images.githubusercontent.com/46322585/73481148-318a5d80-4369-11ea-8ba4-147610d2a45b.png)

**Comment by netfoundry-ui** [comment]
Fixed in the March 3 Push
