### ISSUE TITLE
assets/images/Login.jpg is 8mb

### ISSUE THREAD

**Issue by dovholuknf** [netfoundry/ziti-console#5]
i made a ZEDE today and happened to have the developer tools open and noticed that this image is a whopping 8mb and took a little while to download. assets/images/Login.jpg it doesn't seem to be displayed either?

**Comment by dovholuknf** [comment]
when the server is slow - this can take a really long time to deliver. multiple seconds. it also seems to be coming down for _*ALL*_ pages too...

**Comment by JeremyTellier** [comment]
Assets optimized in latest push
